# Generated by Django 4.2.3 on 2023-07-30 20:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 30, 20, 29, 25, 177606)
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 30, 20, 29, 25, 177617)
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(default=None, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
